version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # Pull image from docker hub
      - run: docker pull jonahtn/train:first

      # Run container
      - run: docker container run jonahtn/train:first
      
      - store_test_results:
        path: /tmp/test-results