version: 2
jobs:
  build:
    docker:
      - image: docker

    working_directory: ~/repo

    steps:
      - checkout
      - docker pull jonahtn/train:first
      - docker container run jonahtn/train:first